### ISSUE TITLE
Comutação

### ISSUE THREAD

**Issue by rodrigofegui** [rodrigofegui/IA-proj1#2]
## Descrição
Considerando 2 indivíduos, realizar a comutação considerando apenas 2 ponto de corte entre seus genes.

Infelizmente há complicações na comutação com 1 ponto de corte, considere os seguintes indivíduos (aleatórios):
9 | 7 | 6 | 3 | 4 | 8 | 5 | 1 | 0 | 2
9 | 1 | 7 | 0 | 6 | 4 | 5 | 3 | 2 | 8

Se permutar no indíce 4 (corte na 3, visto que o primeiro é fixo), por exemplo, ficaria:
9 | 7 | 6 | **0** | 4 | 8 | 5 | 1 | ~~0~~ | 2
9 | 1 | 7 | **3** | 6 | 4 | 5 | ~~3~~ | 2 | 8
o que causaria duplicata em ambos os filhos, o que não pode.

Se considerar blocos no índice 4, por exemplo, ficaria:
9 | **1** | **7** | **0** | 4 | 8 | 5 | ~~1~~ | ~~0~~ | 2
9 | **7** | **6** | **3** | ~~6~~ | 4 | 5 | ~~3~~ | 2 | 8
também ocorrerá duplicatas.

Por isso, alguma comutação de 2 pontos deve ser implementada.

## Critérios de aceitação
- [x] Comutar 2 indivíduos
- [x] Não retornar filhos com duplicatas

**Comment by gust-luiz** [comment]
Primeira implementação no commit b9edef1eda4b81630d5713ffa4eaf0e45811702b
