### ISSUE TITLE
Mutação

### ISSUE THREAD

**Issue by rodrigofegui** [rodrigofegui/IA-proj1#3]
## Descrição
Considerando 1 indivíduos, realizar a mutação em 2 pontos, conforme demonstrado abaixo:
9 | 5 | 4 | 1 | 0 | 7 | 8 | 6 | 3 | 2

Com mutações nos índices 6 e 8, resultaria em:
9 | 5 | 4 | 1 | 0 | **6** | 8 | **7** | 3 | 2

## Critérios de aceitação
- [x] Mutar 1 indivíduo

**Comment by gust-luiz** [comment]
Resolução da tarefa **Mutar 1 indivíduo** no commit f88a0972bd7791667625aaf88fad23341339121a
